configurations:
  help_message: 'I broke captcha using your URL :)'
  action_name: 'broke_captcha'
  metropolitan_url: 'https://metropolis-api-captcha.p.mashape.com/solve?image='
  Mashape_Key: KiXBo8fKMomshjj7AbOwAQ09dcXnp1CJYXxjsniJFdDg8ivPno
