configurations:
  help_message: 'Seach videos of youtube, just call: youtube "your search" max:ReusultsThatYouWant. Example: youtube search me and you'
  action_name: 'youtube'
  wiki: 'Write any words about your extension'
  youtube_username: 'lscorza'
  youtube_key: 'AIzaSyDYOu414h7AJaZdRPc1qPlzmGP_vcwwG4Y'
  MashapeKey: 'KiXBo8fKMomshjj7AbOwAQ09dcXnp1CJYXxjsniJFdDg8ivPno'